from __future__ import annotations

from typing import Dict, List

from smolagents import tool

TASK_TYPE_MAP = {
    # closed-book extraction / "answer is in the text" tasks
    "give the names": "retrieval_task",
    "list": "retrieval_task",
    "identify": "retrieval_task",
    "mentioned": "retrieval_task",
    "according to": "retrieval_task",
    "in the text": "retrieval_task",
    "in the prompt": "retrieval_task",
    "文中": "retrieval_task",
    "题目中": "retrieval_task",
    "提到": "retrieval_task",
    "列出": "retrieval_task",
    "给出": "retrieval_task",
    "名称": "retrieval_task",
    "derive": "derive",
    "derivation": "derive",
    "mechanism": "mechanism_inference",
    "model": "mechanism_inference",
    "pathway": "pathway_mapping",
    "upstream": "pathway_mapping",
    "downstream": "pathway_mapping",
    "epistasis": "pathway_mapping",
    "experiment": "design_wetlab",
    "protocol": "design_wetlab",
    "simulation": "design_insilico",
    "compute": "design_insilico",
    "analysis": "design_data_analysis",
    "analyze": "design_data_analysis",
    "compare": "comparison_table",
    "contrast": "comparison_table",
    "critique": "critique_and_tradeoff",
    "trade-off": "critique_and_tradeoff",
    "tradeoff": "critique_and_tradeoff",
    "estimate": "parameter_estimation",
    "sanity": "sanity_check",
    "limitation": "sanity_check",
    "synthesis": "synthesis",
}


def _infer_task_type(text: str) -> str:
    lowered = text.lower()
    for key, value in TASK_TYPE_MAP.items():
        if key in lowered:
            return value
    return "mechanism_inference"


def _build_tasks(problem_text: str, context_brief: Dict) -> List[Dict]:
    subquestions = context_brief.get("subquestions") or []
    if not subquestions:
        subquestions = [problem_text.strip()]

    tasks = []
    for idx, item in enumerate(subquestions, start=1):
        task_type = _infer_task_type(item)
        title = item.strip()
        if not title:
            title = f"Analyze subtask {idx}"
        tasks.append({
            "id": f"T{idx}",
            "title": title if title[0].isalpha() else f"Analyze task {idx}",
            "task_type": task_type,
            "inputs": context_brief.get("key_terms", []) + context_brief.get("entities", []),
            "deliverable": item.strip() or "Structured response",
            "depends_on": [],
            "roles": [],
        })
    return tasks


@tool
def build_task_graph_tool(problem_text: str, context_brief: dict) -> dict:
    """
    Build a lightweight ResearchTaskGraph from problem text and ContextBrief.

    Args:
        problem_text: Original problem text.
        context_brief: ContextBrief JSON.

    Returns:
        ResearchTaskGraph JSON.
    """
    tasks = _build_tasks(problem_text, context_brief)
    return {"tasks": tasks, "notes": ["Generated by deterministic task-graph tool."]}
